### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

### ISSUE THREAD

**Issue by vladimirmyshkovski** [anapaulagomes/pytest-picked#16] opened 2018-10-21 10:28 UTC
I'm trying to run pytest in docker container. I always use pytest in my projects with docker.
Is the `.git` folder missing in the container?

This is my `.dockerignore`:
```

.*
!.coveragerc
!.env
!.pylintrc

```

This is traceback:
```

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 174, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/config/__init__.py", line 593, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 306, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_picked/plugin.py", line 45, in pytest_configure
INTERNALERROR>     picked_files, picked_folders = mode.affected_tests()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_picked/modes.py", line 12, in affected_tests
INTERNALERROR>     raw_output = self.git_output()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_picked/modes.py", line 31, in git_output
INTERNALERROR>     output = subprocess.run(self.command(), stdout=subprocess.PIPE)
INTERNALERROR>   File "/usr/local/lib/python3.6/subprocess.py", line 403, in run
INTERNALERROR>     with Popen(*popenargs, **kwargs) as process:
INTERNALERROR>   File "/usr/local/lib/python3.6/subprocess.py", line 709, in __init__
INTERNALERROR>     restore_signals, start_new_session)
INTERNALERROR>   File "/usr/local/lib/python3.6/subprocess.py", line 1344, in _execute_child
INTERNALERROR>     raise child_exception_type(errno_num, err_msg, err_filename)
INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

```

**Comment by anapaulagomes** [comment] 2018-10-21 14:47
Hi @narnikgamarnikus, thanks for being in touch. I haven't tested `pytest-picked` on a docker container but if I'm afraid it isn't possible since the plugin relays on [`subprocess`](https://github.com/anapaulagomes/pytest-picked/blob/dc54148f7d771b14080f2ff9740a2c4269b7c868/pytest_picked/modes.py#L31). In this case, it will try to find `git` inside of your container but it will be on your local machine. How are you running the tests?

**Comment by narnikgamarnikus** [comment] 2018-10-21 17:07
Hi @anapaulagomes, thanks for the quick response!

I run tests like this:
`docker-compose -f local.yml run --rm django pytest . -s`

**Comment by anapaulagomes** [comment] 2018-10-22 12:30
I think that whenever you call `git` it will try to find the `.git` folder. The issue is similar to this other one in this library https://github.com/madjar/nox/issues/36 (meaning: `git` is a dependency to `pytest-picked`. We can try to find a way of running it inside of a container, like installing it and copying the folder... no idea if it's gonna work. In the end sounds like a hack. Feel free to bring suggestions (or a PR hehe) on this topic. :)

**Comment by pschroeder89** [comment] 2021-01-31 01:52
I know this is an old ticket, but I figured I'd chime in. 
I agree with @anapaulagomes, this isn't really a bug in this repo but in the implementation. 
Within your docker image, you need to have git installed, and you'd need to have your entire test repo directory in the image as well (including the .git directory). Otherwise, pytest-picked would have no way of comparing the files in your container against the files in your master branch.

**Comment by anapaulagomes** [comment] 2021-01-31 08:59
That's correct, @pschroeder89. I'll close this issue since the question's been clarified.

**Closed by anapaulagomes** 2021-01-31 08:59 UTC
Labels: hacktoberfest, help wanted

**Comment by Jureong** [comment] 2022-01-13 08:41
If you hasnt installed git, 
`sudo apt-get install git`
